# Week 3 NPTEL Practice

R Prog Lab - Purvaj Gaonkar - 23102C0083

**Topics**
- Calculations with data vectors: addition, subtraction, multiplication, division
- Power operations, integer and modulo division
- Built-in functions and assignments
- Matrices

In [1]:
R.version.string

[1] "R version 4.6.1 (2026-06-24)"

---
## Calculations with data vectors

Arithmetic on a vector is applied element by element.

In [2]:
x <- c(2, 4, 6, 8, 10)
x

[1]  2  4  6  8 10

In [3]:
x + 5

[1]  7  9 11 13 15

In [4]:
x - 5

[1] -3 -1  1  3  5

In [5]:
x * 2

[1]  4  8 12 16 20

In [6]:
x / 2

[1] 1 2 3 4 5

### Two vectors of the same length

In [7]:
y <- c(1, 2, 3, 4, 5)
x + y

[1]  3  6  9 12 15

In [8]:
x - y

[1] 1 2 3 4 5

In [9]:
x * y

[1]  2  8 18 32 50

In [10]:
x / y

[1] 2 2 2 2 2

### Recycling

A shorter vector is reused from the start until it lines up with the longer one.

In [11]:
c(1, 2, 3, 4, 5, 6) + c(10, 20)

[1] 11 22 13 24 15 26

In [12]:
c(1, 2, 3, 4, 5, 6) * c(1, 2, 3)

[1]  1  4  9  4 10 18

If the longer length is not a multiple of the shorter one, R still recycles but warns.

In [13]:
c(1, 2, 3, 4, 5) + c(10, 20)

Warning message in c(1, 2, 3, 4, 5) + c(10, 20):
“longer object length is not a multiple of shorter object length”

[1] 11 22 13 24 15

---
## Power operations

In [14]:
2^3

[1] 8

In [15]:
2**3

[1] 8

In [16]:
x^2

[1]   4  16  36  64 100

In [17]:
x^0.5

[1] 1.414214 2.000000 2.449490 2.828427 3.162278

In [18]:
sqrt(x)

[1] 1.414214 2.000000 2.449490 2.828427 3.162278

In [19]:
(-8)^(1/3)

[1] NaN

A negative base with a fractional exponent gives NaN, because R works in real numbers here.

---
## Integer and modulo division

`%/%` returns the whole-number part of a division. `%%` returns the remainder.

In [20]:
17 / 5

[1] 3.4

In [21]:
17 %/% 5

[1] 3

In [22]:
17 %% 5

[1] 2

In [23]:
c(10, 11, 12, 13, 14) %% 3

[1] 1 2 0 1 2

In [24]:
c(10, 11, 12, 13, 14) %/% 3

[1] 3 3 4 4 4

### Negative numbers

In [25]:
-17 %/% 5

[1] -4

In [26]:
-17 %% 5

[1] 3

R rounds the integer division downwards, so the remainder takes the sign of the divisor.

### A common use: testing divisibility

In [27]:
x %% 2 == 0

[1] TRUE TRUE TRUE TRUE TRUE

---
## Built-in functions

In [28]:
v <- c(4, 8, 15, 16, 23, 42)
v

[1]  4  8 15 16 23 42

In [29]:
sum(v)

[1] 108

In [30]:
prod(c(1, 2, 3, 4))

[1] 24

In [31]:
mean(v)

[1] 18

In [32]:
median(v)

[1] 15.5

In [33]:
var(v)

[1] 182

In [34]:
sd(v)

[1] 13.49074

In [35]:
min(v)

[1] 4

In [36]:
max(v)

[1] 42

In [37]:
range(v)

[1]  4 42

In [38]:
length(v)

[1] 6

### Rounding

In [39]:
round(3.14159, 2)

[1] 3.14

In [40]:
ceiling(3.2)

[1] 4

In [41]:
floor(3.8)

[1] 3

In [42]:
trunc(-3.8)

[1] -3

In [43]:
signif(123456, 3)

[1] 123000

### Logs and exponentials

In [44]:
exp(1)

[1] 2.718282

In [45]:
log(100)

[1] 4.60517

In [46]:
log(100, base = 10)

[1] 2

In [47]:
log10(100)

[1] 2

In [48]:
log2(8)

[1] 3

### Cumulative functions

In [49]:
cumsum(1:6)

[1]  1  3  6 10 15 21

In [50]:
cumprod(1:6)

[1]   1   2   6  24 120 720

In [51]:
cummax(c(3, 1, 5, 2, 9, 4))

[1] 3 3 5 5 9 9

### Sorting

In [52]:
sort(v, decreasing = TRUE)

[1] 42 23 16 15  8  4

In [53]:
order(c(30, 10, 20))

[1] 2 3 1

---
## Assignments

In [54]:
a <- 10
a

[1] 10

In [55]:
b = 20
b

[1] 20

In [56]:
30 -> d
d

[1] 30

In [57]:
assign("e", 40)
e

[1] 40

### Assigning into part of a vector

In [58]:
v[2] <- 99
v

[1]  4 99 15 16 23 42

In [59]:
v[c(1, 3)] <- 0
v

[1]  0 99  0 16 23 42

---
## Matrices

A matrix is a vector arranged into rows and columns. R fills it column by column unless told otherwise.

In [60]:
m <- matrix(1:6, nrow = 2)
m

     [,1] [,2] [,3]
[1,] 1    3    5
[2,] 2    4    6

In [61]:
matrix(1:6, nrow = 2, byrow = TRUE)

     [,1] [,2] [,3]
[1,] 1    2    3
[2,] 4    5    6

In [62]:
matrix(1:6, ncol = 2)

     [,1] [,2]
[1,] 1    4
[2,] 2    5
[3,] 3    6

### Dimensions

In [63]:
dim(m)

[1] 2 3

In [64]:
nrow(m)

[1] 2

In [65]:
ncol(m)

[1] 3

### Naming rows and columns

In [66]:
dimnames(m) <- list(c("r1", "r2"), c("c1", "c2", "c3"))
m

   c1 c2 c3
r1 1  3  5
r2 2  4  6

### Building a matrix from vectors

In [67]:
rbind(c(1, 2, 3), c(4, 5, 6))

     [,1] [,2] [,3]
[1,] 1    2    3
[2,] 4    5    6

In [68]:
cbind(c(1, 2), c(3, 4), c(5, 6))

     [,1] [,2] [,3]
[1,] 1    3    5
[2,] 2    4    6

### Turning a vector into a matrix with dim()

In [69]:
z <- 1:6
dim(z) <- c(2, 3)
z

     [,1] [,2] [,3]
[1,] 1    3    5
[2,] 2    4    6