# Week 9 NPTEL Practice
**Foundations of R Software**

R Prog Lab - Purvaj Gaonkar - 23102C0083

**Strings: Display and Formatting**
- Print and format with concatenate: `cat()`
- The `paste()` and `paste0()` functions
- String splitting: `strsplit()`
- Manipulations with strings: `nchar()`, `nzchar()`, `toupper()`, `tolower()`

In [1]:
R.version.string

[1] "R version 4.6.1 (2026-06-24)"

---
## The limitation of print()

The goal is to print one line: *The zero occurs at 2\*pi radians.*

`print()` handles only one object at a time. Passing three raises an error, because the second and third arguments are matched to `print()`'s own parameters rather than printed. The error is caught here so the notebook keeps running.

In [2]:
tryCatch(
  print("The zero occurs at", 2*pi, "radians."),
  error = function(e) cat("Error:", conditionMessage(e), "\n")
)

Error: invalid 'quote' argument

### One at a time

In [3]:
print("The zero occurs at"); print(2*pi); print("radians")

[1] "The zero occurs at"
[1] 6.283185
[1] "radians"

It works, but gives three separate lines with quotes and index markers.

---
## cat()

`cat()` converts its arguments to character, joins them in sequence, and writes a single continuous output. It puts a space between items by default and does not add a newline, so `\n` has to be supplied.

In [4]:
cat("The zero occurs at", 2*pi, "radians.", "\n")

The zero occurs at 6.283185 radians.

### Without the newline

In [5]:
cat("no newline here")
cat("so this runs on")

no newline hereso this runs on

In [6]:
cat("with a newline\n")
cat("this starts fresh\n")

with a newline
this starts fresh

### Mixing text and calculated values

In [7]:
d = date()
cat("Today's date is:", d, "\n")

Today's date is: Mon Sep 21 08:37:23 2026

In [8]:
x = 7
cat("The square of", x, "is", x^2, "!\n")

The square of 7 is 49 !

In [9]:
cat("The square root of", x, "is approximately", format(sqrt(x), digits = 3), "\n")

The square root of 7 is approximately 2.65

`format()` returns a string, so it nests inside `cat()` to control the digits.

### Printing a vector

In [10]:
evenno = c(2, 4, 6, 8, 10)
evenno

[1]  2  4  6  8 10

In [11]:
cat("The first few even numbers are:", evenno, "...\n")

The first few even numbers are: 2 4 6 8 10 ...

---
## The sep argument

`sep` replaces the default space between items.

In [12]:
x = 1:10
cat(x, sep = " ++ ")

1 ++ 2 ++ 3 ++ 4 ++ 5 ++ 6 ++ 7 ++ 8 ++ 9 ++ 10

In [13]:
cat("\n")

In [14]:
cat(x, sep = " / ")

1 / 2 / 3 / 4 / 5 / 6 / 7 / 8 / 9 / 10

In [15]:
cat("\n")

In [16]:
cat("a", "b", "c", sep = "")

abc

In [17]:
cat("\n")

In [18]:
cat("a", "b", "c", sep = "\n")

a
b
c

---
## fill and labels

`fill` breaks the output into lines of a given width. `labels` prefixes each line.

In [19]:
x = 1:10
cat(x, fill = 2, labels = paste("(", letters[1:10], "):"))

( a ): 1
( b ): 2
( c ): 3
( d ): 4
( e ): 5
( f ): 6
( g ): 7
( h ): 8
( i ): 9
( j ): 10

---
## cat() against print()

In [20]:
result_print = print("hello")

[1] "hello"

In [21]:
result_print

[1] "hello"

In [22]:
result_cat = cat("hello\n")

hello

In [23]:
result_cat

NULL

`print()` returns its value, so it can be stored. `cat()` returns NULL: it only writes output. That is why `paste()`, next, exists.

---
## paste()

`paste()` joins strings end to end and **returns** the result, so unlike `cat()` it can be assigned to a variable. It converts arguments with `as.character()` and inserts a space by default.

In [24]:
paste("Everybody", "loves", "R Programming.")

[1] "Everybody loves R Programming."

### Changing the separator

In [25]:
paste("Everybody", "loves", "R Programming.", sep = "*")

[1] "Everybody*loves*R Programming."

In [26]:
paste("Everybody", "loves", "R Programming.", sep = "===")

[1] "Everybody===loves===R Programming."

In [27]:
paste("Everybody", "loves", "R Programming.", sep = "")

[1] "EverybodylovesR Programming."

### paste converts to character

In [28]:
paste(1:12)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12"

In [29]:
as.character(1:12)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12"

On a single vector the two are identical.

### Storing the result

In [30]:
msg = paste("The answer is", 42)
msg

[1] "The answer is 42"

In [31]:
class(msg)

[1] "character"

---
## paste() with vectors

When an argument is a vector, `paste()` works term by term and returns a vector. Shorter arguments are recycled.

In [32]:
names = c("Prof. Singh", "Mr. Venkat", "Dr. Jha")
names

[1] "Prof. Singh" "Mr. Venkat"  "Dr. Jha"

In [33]:
paste(names, "is", "a good", "person.")

[1] "Prof. Singh is a good person." "Mr. Venkat is a good person."
[3] "Dr. Jha is a good person."

In [34]:
length(paste(names, "is", "a good", "person."))

[1] 3

---
## collapse

`collapse` takes the vector that `paste()` produced and joins its elements into one string, using the given separator.

In [35]:
paste(names, "is", "a good", "person.", collapse = ", and ")

[1] "Prof. Singh is a good person., and Mr. Venkat is a good person., and Dr. Jha is a good person."

In [36]:
length(paste(names, "is", "a good", "person.", collapse = ", and "))

[1] 1

### sep against collapse

`sep` goes between the arguments within each element. `collapse` goes between the finished elements.

In [37]:
x = paste("Ex", 1:5, sep = "_")
x

[1] "Ex_1" "Ex_2" "Ex_3" "Ex_4" "Ex_5"

In [38]:
x[1]

[1] "Ex_1"

In [39]:
x[3]

[1] "Ex_3"

In [40]:
x[5]

[1] "Ex_5"

In [41]:
x = paste("Ex", 1:5, sep = "_", collapse = "")
x

[1] "Ex_1Ex_2Ex_3Ex_4Ex_5"

In [42]:
x[1]

[1] "Ex_1Ex_2Ex_3Ex_4Ex_5"

In [43]:
length(x)

[1] 1

With `collapse` the result is a single string of length 1, so `x[1]` is the whole thing.

In [44]:
paste("Ex", 1:5, sep = "_", collapse = " | ")

[1] "Ex_1 | Ex_2 | Ex_3 | Ex_4 | Ex_5"

---
## Spaces inside the quotes

`sep` is inserted exactly as given, and spaces already inside the strings are kept. Compare these two.

In [45]:
paste(1, " is first", 2, " is second", 3, " is third", sep = "#")

[1] "1# is first#2# is second#3# is third"

In [46]:
paste(1, " is first ", 2, " is second ", 3, " is third ", sep = "#")

[1] "1# is first #2# is second #3# is third "

---
## paste0()

`paste0()` is `paste()` with `sep = ""`, so nothing is inserted between arguments.

In [47]:
paste0(1:10)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

In [48]:
paste(1:10)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

On a single vector the two agree.

### Where they differ

In [49]:
paste0(1:10, c("st", "nd", "rd", rep("th", 7)))

 [1] "1st"  "2nd"  "3rd"  "4th"  "5th"  "6th"  "7th"  "8th"  "9th"  "10th"

In [50]:
paste(1:10, c("st", "nd", "rd", rep("th", 7)))

 [1] "1 st"  "2 nd"  "3 rd"  "4 th"  "5 th"  "6 th"  "7 th"  "8 th"  "9 th"
[10] "10 th"

`paste()` puts a space between the number and its suffix. `paste0()` does not.

In [51]:
paste0("file_", 1:3, ".csv")

[1] "file_1.csv" "file_2.csv" "file_3.csv"

---
## strsplit()

`strsplit(x, split)` breaks each element of a character vector into pieces at the split string. It always returns a **list**, one element per input string.

In [52]:
x = "The&!syntax&!of&!paste&!is!&available! &inthe online-help"
x

[1] "The&!syntax&!of&!paste&!is!&available! &inthe online-help"

### Splitting on one character

In [53]:
strsplit(x, split = "!")

[[1]]
[1] "The&"                "syntax&"             "of&"
[4] "paste&"              "is"                  "&available"
[7] " &inthe online-help"

### Splitting on a string

In [54]:
strsplit(x, split = "&!")

[[1]]
[1] "The"                               "syntax"
[3] "of"                                "paste"
[5] "is!&available! &inthe online-help"

The split string is matched as a whole. `&!` and `!&` are different separators, and the result changes accordingly.

In [55]:
y = strsplit(x, split = "!&")
y

[[1]]
[1] "The&!syntax&!of&!paste&!is"    "available! &inthe online-help"

### Accessing the pieces

The result is a list, so `[[1]]` reaches the vector inside it, and `[n]` then picks a piece.

In [56]:
y[[1]][1]

[1] "The&!syntax&!of&!paste&!is"

In [57]:
y[[1]][2]

[1] "available! &inthe online-help"

In [58]:
y[[1]][3]

[1] NA

Only two pieces exist, so asking for a third returns NA rather than an error.

In [59]:
class(y)

[1] "list"

In [60]:
length(y[[1]])

[1] 2

### Splitting into single characters

In [61]:
strsplit("R course", split = "")

[[1]]
[1] "R" " " "c" "o" "u" "r" "s" "e"

---
## strsplit() on a vector, then into a matrix

In [62]:
dates = c("2020-07-24", "2021-08-25", "2022-09-26", "2023-10-27")
dates

[1] "2020-07-24" "2021-08-25" "2022-09-26" "2023-10-27"

In [63]:
datesplt = strsplit(dates, "-")
datesplt

[[1]]
[1] "2020" "07"   "24"

[[2]]
[1] "2021" "08"   "25"

[[3]]
[1] "2022" "09"   "26"

[[4]]
[1] "2023" "10"   "27"

Four input strings give a list of four, each holding year, month and day.

### Flattening into a character matrix

In [64]:
datemat = matrix(unlist(datesplt), nrow = 4, ncol = 3, byrow = TRUE)
datemat

     [,1] [,2] [,3]
[1,] 2020 07   24
[2,] 2021 08   25
[3,] 2022 09   26
[4,] 2023 10   27

`byrow = TRUE` is essential. `unlist()` produces year, month, day, year, month, day and so on, so filling by row keeps each date on its own row.

In [65]:
class(datemat[1, 1])

[1] "character"

### As a numeric matrix

In [66]:
datematrix = matrix(as.numeric(unlist(datesplt)), nrow = 4, ncol = 3, byrow = TRUE)
datematrix

     [,1] [,2] [,3]
[1,] 2020  7   24
[2,] 2021  8   25
[3,] 2022  9   26
[4,] 2023 10   27

In [67]:
class(datematrix[1, 1])

[1] "numeric"

`as.numeric()` turns `"07"` into `7`, dropping the leading zero, and makes arithmetic possible.

In [68]:
colnames(datematrix) = c("Year", "Month", "Day")
datematrix

     Year Month Day
[1,] 2020  7    24
[2,] 2021  8    25
[3,] 2022  9    26
[4,] 2023 10    27

In [69]:
datematrix[, "Year"] + 1

[1] 2021 2022 2023 2024

---
## nchar(): counting characters

`nchar()` returns the number of characters in each element. Spaces and punctuation count.

In [70]:
x = "R course 24.07.2022"
y = "Number of participants: 25"

In [71]:
nchar(x)

[1] 19

In [72]:
nchar(y)

[1] 26

### On a vector

In [73]:
nchar(c("Apple", "Banana", "Cake"))

[1] 5 6 4

### On numbers

Numbers are converted to character first, so `nchar()` counts digits and the decimal point.

In [74]:
nchar(c(2, 4, 6))

[1] 1 1 1

In [75]:
nchar(c(11, 222, 3333))

[1] 2 3 4

In [76]:
nchar(c(1.1, 2.22, 3.333))

[1] 3 4 5

`1.1` has three characters: 1, the point, and 1.

### nchar is not length

In [77]:
fruits = c("Apple", "Banana", "Cake")
length(fruits)

[1] 3

In [78]:
nchar(fruits)

[1] 5 6 4

`length()` counts elements. `nchar()` counts characters within each element.

---
## nzchar(): non-empty strings

`nzchar()` returns TRUE for each element that is not an empty string. It is a fast check for blanks.

In [79]:
nzchar(x)

[1] TRUE

In [80]:
nzchar(y)

[1] TRUE

In [81]:
nzchar(c("Apple", "Banana", "Cake"))

[1] TRUE TRUE TRUE

In [82]:
z = c("Apple", "", "Cake")
nzchar(z)

[1]  TRUE FALSE  TRUE

In [83]:
z[nzchar(z)]

[1] "Apple" "Cake"

Used as an index it drops the empty strings.

### A space is not empty

In [84]:
nzchar(c("", " "))

[1] FALSE  TRUE

---
## toupper() and tolower()

Convert case. Characters that are not letters are left as they are.

In [85]:
x = "R course will start from 24.07.2022"
toupper(x)

[1] "R COURSE WILL START FROM 24.07.2022"

In [86]:
z = "INDIAN INSTITUTE OF TECHNOLOGY"
tolower(z)

[1] "indian institute of technology"

In [87]:
toupper(c("apple", "banana", "cake"))

[1] "APPLE"  "BANANA" "CAKE"

### Case-insensitive comparison

In [88]:
"Apple" == "apple"

[1] FALSE

In [89]:
tolower("Apple") == tolower("apple")

[1] TRUE

---
## Putting it together

In [90]:
students = c("amy", "ram", "li")
marks = c(91, 72, 88)

for (i in seq_along(students)) {
  cat(format(toupper(students[i]), width = 6),
      "scored", marks[i],
      "(", nchar(students[i]), "letters in name )\n")
}

AMY    scored 91 ( 3 letters in name )
RAM    scored 72 ( 3 letters in name )
LI     scored 88 ( 2 letters in name )

In [91]:
report = paste0(toupper(students), ":", marks)
report

[1] "AMY:91" "RAM:72" "LI:88"

In [92]:
paste(report, collapse = "; ")

[1] "AMY:91; RAM:72; LI:88"

---
## Summary

| Task | Command |
|---|---|
| Print several items on one line | `cat(a, b, c, "\n")` |
| Change the separator | `cat(x, sep = " / ")` |
| Label wrapped lines | `cat(x, fill = n, labels = )` |
| Join strings and keep the result | `paste(a, b, sep = " ")` |
| Join with no separator | `paste0(a, b)` |
| Join a vector into one string | `paste(x, collapse = ", ")` |
| Split a string | `strsplit(x, split = "-")` |
| Reach a piece | `strsplit(x, "-")[[1]][2]` |
| Split results into a matrix | `matrix(unlist(s), nrow = , byrow = TRUE)` |
| Count characters | `nchar(x)` |
| Test for non-empty | `nzchar(x)` |
| Change case | `toupper(x)`, `tolower(x)` |

Four things worth carrying forward:

1. `cat()` writes output and returns NULL. `paste()` returns a string you can store.
2. `sep` goes between arguments inside each element; `collapse` joins the finished
   elements into one string of length 1.
3. `strsplit()` always returns a list, so reach the pieces with `[[1]][n]`.
4. `nchar()` counts characters within each element; `length()` counts elements.