# Week 4 NPTEL Practice

R Prog Lab - Purvaj Gaonkar - 23102C0083

**Topics**
- Matrix operations: row, column and other operations
- Matrix operations: access and mathematical operations
- Logical operators
- Relational and logical operators

In [1]:
R.version.string

[1] "R version 4.6.1 (2026-06-24)"

---
## Setting up a matrix

In [2]:
m <- matrix(1:12, nrow = 3)
m

     [,1] [,2] [,3] [,4]
[1,] 1    4    7    10
[2,] 2    5    8    11
[3,] 3    6    9    12

In [3]:
dim(m)

[1] 3 4

---
## Accessing elements

In [4]:
m[2, 3]

[1] 8

In [5]:
m[1, ]

[1]  1  4  7 10

In [6]:
m[, 2]

[1] 4 5 6

In [7]:
m[1:2, 2:3]

     [,1] [,2]
[1,] 4    7
[2,] 5    8

In [8]:
m[-1, ]

     [,1] [,2] [,3] [,4]
[1,] 2    5    8    11
[2,] 3    6    9    12

In [9]:
m[, -c(1, 2)]

     [,1] [,2]
[1,] 7    10
[2,] 8    11
[3,] 9    12

### drop = FALSE keeps the result a matrix

In [10]:
m[1, ]

[1]  1  4  7 10

In [11]:
m[1, , drop = FALSE]

     [,1] [,2] [,3] [,4]
[1,] 1    4    7    10

---
## Row and column operations

In [12]:
rowSums(m)

[1] 22 26 30

In [13]:
colSums(m)

[1]  6 15 24 33

In [14]:
rowMeans(m)

[1] 5.5 6.5 7.5

In [15]:
colMeans(m)

[1]  2  5  8 11

### apply()

`apply(X, 1, f)` works across rows, `apply(X, 2, f)` works down columns.

In [16]:
apply(m, 1, sum)

[1] 22 26 30

In [17]:
apply(m, 2, sum)

[1]  6 15 24 33

In [18]:
apply(m, 2, max)

[1]  3  6  9 12

In [19]:
apply(m, 1, function(r) r * 2)

     [,1] [,2] [,3]
[1,]  2    4    6
[2,]  8   10   12
[3,] 14   16   18
[4,] 20   22   24

---
## Adding and removing rows and columns

In [20]:
rbind(m, c(100, 200, 300, 400))

     [,1] [,2] [,3] [,4]
[1,]   1    4    7   10
[2,]   2    5    8   11
[3,]   3    6    9   12
[4,] 100  200  300  400

In [21]:
cbind(m, c(7, 8, 9))

     [,1] [,2] [,3] [,4] [,5]
[1,] 1    4    7    10   7
[2,] 2    5    8    11   8
[3,] 3    6    9    12   9

In [22]:
m[-2, ]

     [,1] [,2] [,3] [,4]
[1,] 1    4    7    10
[2,] 3    6    9    12

---
## Mathematical operations on matrices

Ordinary arithmetic operators work element by element.

In [23]:
a <- matrix(1:4, nrow = 2)
b <- matrix(5:8, nrow = 2)
a
b

     [,1] [,2]
[1,] 1    3
[2,] 2    4

     [,1] [,2]
[1,] 5    7
[2,] 6    8

In [24]:
a + b

     [,1] [,2]
[1,] 6    10
[2,] 8    12

In [25]:
a - b

     [,1] [,2]
[1,] -4   -4
[2,] -4   -4

In [26]:
a * b

     [,1] [,2]
[1,]  5   21
[2,] 12   32

In [27]:
a / b

     [,1]      [,2]
[1,] 0.2000000 0.4285714
[2,] 0.3333333 0.5000000

### Matrix multiplication

`*` is elementwise. True matrix multiplication uses `%*%`.

In [28]:
a * b

     [,1] [,2]
[1,]  5   21
[2,] 12   32

In [29]:
a %*% b

     [,1] [,2]
[1,] 23   31
[2,] 34   46

### Transpose, determinant, inverse

In [30]:
t(a)

     [,1] [,2]
[1,] 1    2
[2,] 3    4

In [31]:
det(a)

[1] -2

In [32]:
solve(a)

     [,1] [,2]
[1,] -2    1.5
[2,]  1   -0.5

In [33]:
a %*% solve(a)

     [,1] [,2]
[1,] 1    0
[2,] 0    1

### Identity and diagonal

In [34]:
diag(3)

     [,1] [,2] [,3]
[1,] 1    0    0
[2,] 0    1    0
[3,] 0    0    1

In [35]:
diag(a)

[1] 1 4

In [36]:
diag(c(1, 2, 3))

     [,1] [,2] [,3]
[1,] 1    0    0
[2,] 0    2    0
[3,] 0    0    3

### Solving a linear system

In [37]:
A <- matrix(c(2, 1, 1, 3), nrow = 2)
bv <- c(5, 10)
solve(A, bv)

[1] 1 3

---
## Relational operators

In [38]:
x <- c(5, 10, 15, 20)

In [39]:
x > 10

[1] FALSE FALSE  TRUE  TRUE

In [40]:
x < 10

[1]  TRUE FALSE FALSE FALSE

In [41]:
x >= 15

[1] FALSE FALSE  TRUE  TRUE

In [42]:
x <= 5

[1]  TRUE FALSE FALSE FALSE

In [43]:
x == 10

[1] FALSE  TRUE FALSE FALSE

In [44]:
x != 10

[1]  TRUE FALSE  TRUE  TRUE

### Comparing two vectors

In [45]:
c(1, 5, 3) > c(2, 4, 3)

[1] FALSE  TRUE FALSE

### Comparison returns a logical vector you can use as an index

In [46]:
x[x > 10]

[1] 15 20

In [47]:
sum(x > 10)

[1] 2

---
## Logical operators

`&` and `|` work element by element. `&&` and `||` compare only the first element and are meant for `if` conditions.

In [48]:
c(TRUE, TRUE, FALSE) & c(TRUE, FALSE, FALSE)

[1]  TRUE FALSE FALSE

In [49]:
c(TRUE, TRUE, FALSE) | c(TRUE, FALSE, FALSE)

[1]  TRUE  TRUE FALSE

In [50]:
!c(TRUE, FALSE)

[1] FALSE  TRUE

In [51]:
TRUE && FALSE

[1] FALSE

In [52]:
TRUE || FALSE

[1] TRUE

### Combining conditions

In [53]:
x > 5 & x < 20

[1] FALSE  TRUE  TRUE FALSE

In [54]:
x[x > 5 & x < 20]

[1] 10 15

In [55]:
x < 10 | x > 15

[1]  TRUE FALSE FALSE  TRUE

### xor, any, all

In [56]:
xor(TRUE, FALSE)

[1] TRUE

In [57]:
any(x > 18)

[1] TRUE

In [58]:
all(x > 1)

[1] TRUE

### Logical values behave as 1 and 0

In [59]:
sum(c(TRUE, TRUE, FALSE, TRUE))

[1] 3

In [60]:
mean(x > 10)

[1] 0.5

---
## Relational operators on matrices

In [61]:
m > 6

     [,1]  [,2]  [,3] [,4]
[1,] FALSE FALSE TRUE TRUE
[2,] FALSE FALSE TRUE TRUE
[3,] FALSE FALSE TRUE TRUE

In [62]:
m[m > 6]

[1]  7  8  9 10 11 12

In [63]:
which(m > 6)

[1]  7  8  9 10 11 12

In [64]:
which(m > 6, arr.ind = TRUE)

     row col
[1,] 1   3
[2,] 2   3
[3,] 3   3
[4,] 1   4
[5,] 2   4
[6,] 3   4