# Week 10 NPTEL Practice
**Foundations of R Software**

R Prog Lab - Purvaj Gaonkar - 23102C0083

**Topics**
- Substitution and replacement of strings: `sub`, `gsub`, `grep`, `grepl`
- Data frames
- Data frames: creation and operations
- Data frames: attach, subset, split
- Data frames: combining and merging

In [1]:
R.version.string

[1] "R version 4.6.1 (2026-06-24)"

---
## sub(): replace the first match

`sub(old, new, string)` replaces the **first** occurrence of `old` only.

In [2]:
y = "Number of participants: 25"
sub("25", "30", y)

[1] "Number of participants: 30"

In [3]:
y = "Mr. Singh is the smart one. Mr. Singh is funny, too."
y

[1] "Mr. Singh is the smart one. Mr. Singh is funny, too."

In [4]:
sub("Mr. Singh", "Professor Jha", y)

[1] "Professor Jha is the smart one. Mr. Singh is funny, too."

Only the first "Mr. Singh" changed. The second is untouched.

---
## gsub(): replace every match

`gsub()` is a global replace: every occurrence is changed.

In [5]:
gsub("Mr. Singh", "Professor Jha", y)

[1] "Professor Jha is the smart one. Professor Jha is funny, too."

### Side by side

In [6]:
s = "Average temperature of August is 35 ofcourse."

In [7]:
sub("of", "in", s)

[1] "Average temperature in August is 35 ofcourse."

In [8]:
gsub("of", "in", s)

[1] "Average temperature in August is 35 incourse."

`gsub()` also changes the "of" hidden inside "ofcourse". Matching is on characters, not whole words.

### Replacing with nothing

In [9]:
gsub(" ", "", "R course 24.07.2022")

[1] "Rcourse24.07.2022"

---
## grep(): which elements match

`grep(pattern, x)` searches each element of `x` and returns the **indices** of those that match.

In [10]:
str = c("R Course", "exercises", "include examples of R language")

In [11]:
grep("ex", str)

[1] 2 3

In [12]:
grep("ex", str, value = FALSE)

[1] 2 3

### value = TRUE returns the elements instead

In [13]:
grep("ex", str, value = TRUE)

[1] "exercises"                      "include examples of R language"

### Case sensitivity

In [14]:
str = c("R Course", "exercises", "include examples of r language", "in R software.")

In [15]:
grep("R", str, ignore.case = FALSE, value = TRUE)

[1] "R Course"       "in R software."

In [16]:
grep("R", str, ignore.case = TRUE, value = TRUE)

[1] "R Course"                       "exercises"
[3] "include examples of r language" "in R software."

"exercises" matches once case is ignored, because it contains a lowercase r.

In [17]:
grep("R", str, ignore.case = TRUE, value = FALSE)

[1] 1 2 3 4

In [18]:
grep("R", str, ignore.case = FALSE, value = FALSE)

[1] 1 4

### Searching across two strings

In [19]:
x = "R course 24.07.2021"
y = "Number of participants: 25"
c(x, y)

[1] "R course 24.07.2021"        "Number of participants: 25"

In [20]:
grep("our", c(x, y))

[1] 1

In [21]:
grep("Num", c(x, y))

[1] 2

### Character ranges

Square brackets match any one character in the range.

In [22]:
grep("[f-j]", letters)

[1]  6  7  8  9 10

In [23]:
grep("[f-j]", letters, value = TRUE)

[1] "f" "g" "h" "i" "j"

### A near-miss

In [24]:
grep("tion", c("caution", "safety", "illusion", "security", "vacation"))

[1] 1 5

"illusion" ends in "sion", so it does not match "tion".

---
## grepl(): TRUE or FALSE for each element

`grepl()` returns a logical vector, one value per element, rather than positions.

In [25]:
str = c("R Course", "exercises", "include examples of R language")
grepl("R", str)

[1]  TRUE FALSE  TRUE

In [26]:
grepl("ex", str)

[1] FALSE  TRUE  TRUE

### grepl() has no value argument

The slides show `grepl("ex", str, value = T)`. That argument belongs to `grep()` only, and current R rejects it. The error is caught so the notebook keeps running.

In [27]:
tryCatch(
  grepl("ex", str, value = TRUE),
  error = function(e) cat("Error:", conditionMessage(e), "\n")
)

Error: unused argument (value = TRUE)

### grepl() as a filter

In [28]:
str[grepl("ex", str)]

[1] "exercises"                      "include examples of R language"

In [29]:
sum(grepl("ex", str))

[1] 2

---
## Data frames

A data frame combines variables of equal length, with each row holding observations on the same unit. Unlike `cbind()` or `matrix()`, it can hold numbers, strings and factors together, one type per column.

In [30]:
library(MASS)

In [31]:
head(painters)

              Composition Drawing Colour Expression School
Da Udine      10           8      16      3         A
Da Vinci      15          16       4     14         A
Del Piombo     8          13      16      7         A
Del Sarto     12          16       9      8         A
Fr. Penni      0          15       8      0         A
Guilio Romano 15          16       4     14         A

In [32]:
dim(painters)

[1] 54  5

54 painters, rated on four numeric scores plus the school they belong to.

### Row names are not variables

The painter names label the rows. They are not a column of the data.

In [33]:
rownames(painters)

 [1] "Da Udine"        "Da Vinci"        "Del Piombo"      "Del Sarto"
 [5] "Fr. Penni"       "Guilio Romano"   "Michelangelo"    "Perino del Vaga"
 [9] "Perugino"        "Raphael"         "F. Zucarro"      "Fr. Salviata"
[13] "Parmigiano"      "Primaticcio"     "T. Zucarro"      "Volterra"
[17] "Barocci"         "Cortona"         "Josepin"         "L. Jordaens"
[21] "Testa"           "Vanius"          "Bassano"         "Bellini"
[25] "Giorgione"       "Murillo"         "Palma Giovane"   "Palma Vecchio"
[29] "Pordenone"       "Tintoretto"      "Titian"          "Veronese"
[33] "Albani"          "Caravaggio"      "Corregio"        "Domenichino"
[37] "Guercino"        "Lanfranco"       "The Carraci"     "Durer"
[41] "Holbein"         "Pourbus"         "Van Leyden"      "Diepenbeck"
[45] "J. Jordaens"     "Otho Venius"     "Rembrandt"       "Rubens"
[49] "Teniers"         "Van Dyck"        "Bourdon"         "Le Brun"
[53] "Le Suer"         "Poussin"

In [34]:
colnames(painters)

[1] "Composition" "Drawing"     "Colour"      "Expression"  "School"

### Extracting a column with $

In [35]:
painters$Drawing

 [1]  8 16 13 16 15 16 17 16 12 18 13 15 15 14 14 15 15 14 10 12 15 15  8  6  9
[26]  8  9  6 14 14 15 10 14  6 13 17 10 13 17 10 10 15  6 10  8 14  6 13 12 10
[51]  8 16 15 17

In [36]:
is.numeric(painters$Drawing)

[1] TRUE

In [37]:
is.numeric(painters$School)

[1] FALSE

In [38]:
is.factor(painters$School)

[1] TRUE

In [39]:
is.factor(painters$Drawing)

[1] FALSE

### Structure at a glance

In [40]:
str(painters)

'data.frame':	54 obs. of  5 variables:
 $ Composition: int  10 15 8 12 0 15 8 15 4 17 ...
 $ Drawing    : int  8 16 13 16 15 16 17 16 12 18 ...
 $ Colour     : int  16 4 16 9 8 4 4 7 10 12 ...
 $ Expression : int  3 14 7 8 0 14 8 6 4 18 ...
 $ School     : Factor w/ 8 levels "A","B","C","D",..: 1 1 1 1 1 1 1 1 1 1 ...

`str()` gives the dimensions, and the name and type of every column, in one call.

---
## summary()

In [41]:
summary(painters)

  Composition       Drawing          Colour        Expression         School
 Min.   : 0.00   Min.   : 6.00   Min.   : 0.00   Min.   : 0.000   A      :10
 1st Qu.: 8.25   1st Qu.:10.00   1st Qu.: 7.25   1st Qu.: 4.000   D      :10
 Median :12.50   Median :13.50   Median :10.00   Median : 6.000   E      : 7
 Mean   :11.56   Mean   :12.46   Mean   :10.94   Mean   : 7.667   G      : 7
 3rd Qu.:15.00   3rd Qu.:15.00   3rd Qu.:16.00   3rd Qu.:11.500   B      : 6
 Max.   :18.00   Max.   :18.00   Max.   :18.00   Max.   :18.000   C      : 6
                                                                  (Other): 8

Numeric columns get min, quartiles, median, mean and max. A factor column gets a frequency table.

In [42]:
summary(painters$School)

 A  B  C  D  E  F  G  H
10  6  6 10  7  4  7  4

In [43]:
summary(painters$Composition)

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
   0.00    8.25   12.50   11.56   15.00   18.00

---
## Creating a data frame

In [44]:
df1 = data.frame(state    = c("UP", "MP", "AP", "JK"),
                 popnsize = c(1000, 2000, 3000, 4000))
df1

  state popnsize
1 UP    1000
2 MP    2000
3 AP    3000
4 JK    4000

In [45]:
str(df1)

'data.frame':	4 obs. of  2 variables:
 $ state   : chr  "UP" "MP" "AP" "JK"
 $ popnsize: num  1000 2000 3000 4000

In [46]:
df1$popnsize

[1] 1000 2000 3000 4000

In [47]:
df1$popnsize * 2

[1] 2000 4000 6000 8000

### Mixed types are the point

In [48]:
df2 = data.frame(state           = c("UP", "MP", "AP", "JK"),
                 samplesize      = c(100, 200, 300, 400),
                 surveycompleted = c("Yes", "No", "Yes", "No"))
df2

  state samplesize surveycompleted
1 UP    100        Yes
2 MP    200        No
3 AP    300        Yes
4 JK    400        No

In [49]:
str(df2)

'data.frame':	4 obs. of  3 variables:
 $ state          : chr  "UP" "MP" "AP" "JK"
 $ samplesize     : num  100 200 300 400
 $ surveycompleted: chr  "Yes" "No" "Yes" "No"

Each column keeps its own type. A matrix would have coerced every value to character.

### Indexing rows and columns

In [50]:
df2[2, ]

  state samplesize surveycompleted
2 MP    200        No

In [51]:
df2[, 2]

[1] 100 200 300 400

In [52]:
df2[2, 3]

[1] "No"

In [53]:
df2[, "samplesize"]

[1] 100 200 300 400

In [54]:
df2[df2$surveycompleted == "Yes", ]

  state samplesize surveycompleted
1 UP    100        Yes
3 AP    300        Yes

---
## attach() and detach()

`attach()` makes the columns available by name, without the `painters$` prefix.

In [55]:
attach(painters)

In [56]:
summary(School)

 A  B  C  D  E  F  G  H
10  6  6 10  7  4  7  4

In [57]:
summary(Composition)

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
   0.00    8.25   12.50   11.56   15.00   18.00

`detach()` undoes it, after which the bare names no longer exist.

In [58]:
detach(painters)

In [59]:
tryCatch(
  summary(School),
  error = function(e) cat("Error:", conditionMessage(e), "\n")
)

Error: object 'School' not found

Attaching is convenient but risky: if a variable of the same name already exists, it silently takes priority. `painters$School` is always unambiguous.

---
## subset()

In [60]:
subset(painters, School == "F")

           Composition Drawing Colour Expression School
Durer      8           10      10      8         F
Holbein    9           10      16     13         F
Pourbus    4           15       6      6         F
Van Leyden 8            6       6      4         F

`==` is the equality test. A single `=` would be read as an argument name and fail.

### The bracket equivalent

In [61]:
painters[painters[["School"]] == "F", ]

           Composition Drawing Colour Expression School
Durer      8           10      10      8         F
Holbein    9           10      16     13         F
Pourbus    4           15       6      6         F
Van Leyden 8            6       6      4         F

Same result. The trailing comma means "all columns".

In [62]:
subset(painters, Composition <= 6)

              Composition Drawing Colour Expression School
Fr. Penni     0           15       8     0          A
Perugino      4           12      10     4          A
Bassano       6            8      17     0          D
Bellini       4            6      14     0          D
Murillo       6            8      15     4          D
Palma Vecchio 5            6      16     0          D
Caravaggio    6            6      16     0          E
Pourbus       4           15       6     6          F

### Combining conditions

In [63]:
subset(painters, Colour == 16 & School == "A")

           Composition Drawing Colour Expression School
Da Udine   10           8      16     3          A
Del Piombo  8          13      16     7          A

In [64]:
subset(painters, Composition == 10 & Expression < 11)

            Composition Drawing Colour Expression School
Da Udine    10           8      16     3          A
F. Zucarro  10          13       8     8          B
Parmigiano  10          15       6     6          B
Josepin     10          10       6     2          C
J. Jordaens 10           8      16     6          G
Bourdon     10           8       8     4          H

### Dropping columns with select

In [65]:
subset(painters, School == "F", select = c(-3, -5))

           Composition Drawing Expression
Durer      8           10       8
Holbein    9           10      13
Pourbus    4           15       6
Van Leyden 8            6       4

Columns 3 and 5, Colour and School, are removed.

In [66]:
subset(painters, School == "A" & Colour == 4, select = c(-2, -4))

              Composition Colour School
Da Vinci      15          4      A
Guilio Romano 15          4      A
Michelangelo   8          4      A

### Selecting columns by name

In [67]:
subset(painters, School == "F", select = c(Composition, Expression))

           Composition Expression
Durer      8            8
Holbein    9           13
Pourbus    4            6
Van Leyden 8            4

---
## split()

`split()` partitions a data frame by the values of a variable, preferably a factor, returning a list with one data frame per group.

In [68]:
splitted = split(painters, painters$School)

In [69]:
names(splitted)

[1] "A" "B" "C" "D" "E" "F" "G" "H"

In [70]:
splitted$A

                Composition Drawing Colour Expression School
Da Udine        10           8      16      3         A
Da Vinci        15          16       4     14         A
Del Piombo       8          13      16      7         A
Del Sarto       12          16       9      8         A
Fr. Penni        0          15       8      0         A
Guilio Romano   15          16       4     14         A
Michelangelo     8          17       4      8         A
Perino del Vaga 15          16       7      6         A
Perugino         4          12      10      4         A
Raphael         17          18      12     18         A

In [71]:
splitted$H

        Composition Drawing Colour Expression School
Bourdon 10           8      8       4         H
Le Brun 16          16      8      16         H
Le Suer 15          15      4      15         H
Poussin 15          17      6      15         H

In [72]:
is.data.frame(splitted$A)

[1] TRUE

In [73]:
class(splitted)

[1] "list"

The container is a list, and each element of it is a data frame.

In [74]:
sapply(splitted, nrow)

 A  B  C  D  E  F  G  H
10  6  6 10  7  4  7  4

---
## Combining data frames

Three techniques: `cbind()` places columns side by side, `merge()` joins on a common column, and `rbind()` stacks rows.

In [75]:
df1

  state popnsize
1 UP    1000
2 MP    2000
3 AP    3000
4 JK    4000

In [76]:
df2

  state samplesize surveycompleted
1 UP    100        Yes
2 MP    200        No
3 AP    300        Yes
4 JK    400        No

---
## cbind()

In [77]:
cbind(df1, df2)

  state popnsize state samplesize surveycompleted
1 UP    1000     UP    100        Yes
2 MP    2000     MP    200        No
3 AP    3000     AP    300        Yes
4 JK    4000     JK    400        No

`state` appears twice. `cbind()` pastes columns together by position and knows nothing about what they mean.

---
## merge()

`merge()` joins two data frames on a common column, matching rows by value rather than by position.

In [78]:
merge(df1, df2, by = "state")

  state popnsize samplesize surveycompleted
1 AP    3000     300        Yes
2 JK    4000     400        No
3 MP    2000     200        No
4 UP    1000     100        Yes

`state` appears once, and the rows come back sorted alphabetically by the key.

### Why matching by value matters

Shuffle one data frame's rows. `cbind()` then pairs the wrong states together, while `merge()` still gets it right.

In [79]:
df2_shuffled = df2[c(3, 1, 4, 2), ]
df2_shuffled

  state samplesize surveycompleted
3 AP    300        Yes
1 UP    100        Yes
4 JK    400        No
2 MP    200        No

In [80]:
cbind(df1, df2_shuffled)

  state popnsize state samplesize surveycompleted
3 UP    1000     AP    300        Yes
1 MP    2000     UP    100        Yes
4 AP    3000     JK    400        No
2 JK    4000     MP    200        No

In [81]:
merge(df1, df2_shuffled, by = "state")

  state popnsize samplesize surveycompleted
1 AP    3000     300        Yes
2 JK    4000     400        No
3 MP    2000     200        No
4 UP    1000     100        Yes

In the `cbind()` output, UP's population now sits beside AP's sample size. `merge()` is unaffected.

---
## rbind()

`rbind()` stacks two data frames vertically. The column names must match.

In [82]:
df11 = data.frame(state = c("UP", "MP", "AP", "JK"), popnsize = c(1000, 2000, 3000, 4000))
df22 = data.frame(state = c("Bihar", "Delhi", "Punjab"), popnsize = c(100, 200, 300))

In [83]:
df11

  state popnsize
1 UP    1000
2 MP    2000
3 AP    3000
4 JK    4000

In [84]:
df22

  state  popnsize
1 Bihar  100
2 Delhi  200
3 Punjab 300

In [85]:
rbind(df11, df22)

  state  popnsize
1 UP     1000
2 MP     2000
3 AP     3000
4 JK     4000
5 Bihar   100
6 Delhi   200
7 Punjab  300

### Mismatched column names fail

In [86]:
df33 = data.frame(region = c("Goa"), popnsize = c(50))
tryCatch(
  rbind(df11, df33),
  error = function(e) cat("Error:", conditionMessage(e), "\n")
)

Error: names do not match previous names

---
## rbind() and cbind() on vectors

On plain vectors, mixing numbers and strings coerces everything to character.

In [87]:
x = c("Apple", "Oranges", "Banana", "Apricot")
y = c(20, 30, 40, 50)

In [88]:
rbind(x, y)

  [,1]  [,2]    [,3]   [,4]
x Apple Oranges Banana Apricot
y 20    30      40     50

In [89]:
cbind(y, x)

     y  x
[1,] 20 Apple
[2,] 30 Oranges
[3,] 40 Banana
[4,] 50 Apricot

The numbers become `"20"`, `"30"` and so on. A data frame would have kept them numeric.

In [90]:
data.frame(y, x)

  y  x
1 20 Apple
2 30 Oranges
3 40 Banana
4 50 Apricot

---
## Summary

| Task | Command |
|---|---|
| Replace first match | `sub(old, new, x)` |
| Replace every match | `gsub(old, new, x)` |
| Indices of matches | `grep(pattern, x)` |
| Matching elements | `grep(pattern, x, value = TRUE)` |
| Ignore case | `grep(pattern, x, ignore.case = TRUE)` |
| TRUE/FALSE per element | `grepl(pattern, x)` |
| Create a data frame | `data.frame(a = , b = )` |
| Structure | `str(df)` |
| Row and column names | `rownames(df)`, `colnames(df)` |
| Extract a column | `df$col` |
| Refer to columns by name | `attach(df)` ... `detach(df)` |
| Filter rows | `subset(df, condition)` |
| Filter and drop columns | `subset(df, condition, select = c(-2, -4))` |
| Split into groups | `split(df, df$factor)` |
| Side by side | `cbind(df1, df2)` |
| Join on a key | `merge(df1, df2, by = "key")` |
| Stack | `rbind(df1, df2)` |

Four things worth carrying forward:

1. `sub()` replaces the first match, `gsub()` every match, and both match characters
   anywhere, including inside words.
2. `grep()` returns positions by default; add `value = TRUE` for the strings. `grepl()`
   returns TRUE/FALSE and has no `value` argument.
3. `cbind()` pairs rows by position; `merge()` pairs them by the key's value. Only
   `merge()` is safe when row order differs.
4. In `subset()` use `==` and quote factor levels: `School == "A"`, never `School = A`.